### ISSUE TITLE
Colab TPU support, Text file format and cleaning help

### ISSUE THREAD

**Issue by deshwalmahesh** [tanmayb123/BertPreTraining#2]
Hi, I went through your video and found it quite helpful. I am working on a different domain so I have some questions . Hoping you could help:
My typical data samples look  like ` Prove that \sin ^2 \theta + \cos ^2 \theta = 1`, `Explain the work of Mitochondria`, " Complete the chemical reaction Na + Cl \longrightarrow ?`

1. Can we use your code with `TPU` on `Colab`?
2. What are the pre-processing steps used for data cleaning? My data has Special Characters, Numbers
3. Is your input data format file `Line by Line` official format? Is there any difference in results?
]

**Comment by tanmayb123** [comment]
Thanks!

1. I haven’t tested this code on TPU, but it _should_ be able to run with PyTorch Lightning’s TPU feature. However, connecting to, training on, and optimizing for TPUs is notoriously difficult due to a lack of good documentation — a lot of it expects you already know about TPUs, how they work, and how frameworks interact with them.
2. Regardless of the data, the Huggingface tokenizer should be able to automatically tokenize it to be compatible with BERT.
3. The input data format that’s expected is that every line is its own sequence to handle, and you can change this in the `data.py` file.

**Comment by deshwalmahesh** [comment]
Thank you very much for the quick reply. Actually I'm new to `Pytorch` because I prefer `Tensorflow 2` which ahs a good `TPU` support. TBH  I'm having hard times these days switching to `PyTorch`.

I looked at your code and I think you are using `-100` for Masking. Is that right? However [in this code by another Youtuber](https://towardsdatascience.com/masked-language-modelling-with-bert-7d49793e5d2c) he has used `103` for masking ids. Are these same? Same thing has been pointed out by someone else in the comments of that blog.

Also regarding data format, [The code for MLM training `run_mlm.py ` (which gives me lots and lots of errors for random reasons)](https://github.com/huggingface/transformers/tree/master/examples/pytorch/language-modeling), there's a `--line_by_line` flag which basically says that it `False`, it'll collect the whole data and make batches of same size. Have you used that kind of approach too?  Actually my data comes from OCR and there are lots of `\n`'s so I think it'll be good to remove all those in order to make it better.

One more thing, can you just push `requirements.txt` too. Each and every version of transformers are different and each one of them is producing errors.

If it does not work, I'm thinking about training training something like [exBERT: Extending Pre-trained Models with Domain-specific Vocabulary Under Constrained Training Resources](https://aclanthology.org/2020.findings-emnlp.129.pdf) as I have around `5M` unlabelled samples.

**Comment by deshwalmahesh** [comment]
As I told you, there's a version issue:

```
 python train.py 
Traceback (most recent call last):
  File "train.py", line 43, in <module>
    trainer = pl.Trainer(gpus=4, distributed_backend='ddp', max_epochs=4)
  File "/home/admin1/anaconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/env_vars_connector.py", line 38, in insert_env_defaults
    return fn(self, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'distributed_backend'

```
If possible, could you please just upload the requirements file?
